"""Add plans and organization plan_id

Revision ID: 60c300ab1432
Revises: da1ba46c0a88
Create Date: 2026-03-07 13:17:37.926091

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '60c300ab1432'
down_revision = 'da1ba46c0a88'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('plan',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.Column('scan_limit', sa.Integer(), nullable=False),
    sa.Column('price_month', sa.Float(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    with op.batch_alter_table('organization', schema=None) as batch_op:
        batch_op.add_column(sa.Column('plan_id', sa.Integer(), nullable=True))
        batch_op.create_index(batch_op.f('ix_organization_plan_id'), ['plan_id'], unique=False)
        batch_op.create_foreign_key(None, 'plan', ['plan_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('organization', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_index(batch_op.f('ix_organization_plan_id'))
        batch_op.drop_column('plan_id')

    op.drop_table('plan')
    # ### end Alembic commands ###
