"""Add dormant Stripe fields to organization and plan

Revision ID: bc58297b0379
Revises: 60c300ab1432
Create Date: 2026-03-07 16:32:11.174097

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bc58297b0379'
down_revision = '60c300ab1432'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('organization', schema=None) as batch_op:
        batch_op.add_column(sa.Column('stripe_customer_id', sa.String(length=120), nullable=True))
        batch_op.add_column(sa.Column('stripe_subscription_id', sa.String(length=120), nullable=True))
        batch_op.add_column(sa.Column('billing_status', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('current_period_end', sa.DateTime(), nullable=True))
        batch_op.create_index(batch_op.f('ix_organization_stripe_customer_id'), ['stripe_customer_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_organization_stripe_subscription_id'), ['stripe_subscription_id'], unique=False)

    with op.batch_alter_table('plan', schema=None) as batch_op:
        batch_op.add_column(sa.Column('stripe_price_id', sa.String(length=120), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('plan', schema=None) as batch_op:
        batch_op.drop_column('stripe_price_id')

    with op.batch_alter_table('organization', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_organization_stripe_subscription_id'))
        batch_op.drop_index(batch_op.f('ix_organization_stripe_customer_id'))
        batch_op.drop_column('current_period_end')
        batch_op.drop_column('billing_status')
        batch_op.drop_column('stripe_subscription_id')
        batch_op.drop_column('stripe_customer_id')

    # ### end Alembic commands ###
